# Generated by Django 5.0.7 on 2024-07-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify

from base.models import AlphaIDField
from rikishi.constants import DIVISION_LEVELS


def populate_divisions_forwards(apps, schema_editor):
    Division = apps.get_model("rikishi", "Division")  # noqa: N806
    db_alias = schema_editor.connection.alias
    for division in DIVISION_LEVELS:
        Division.objects.using(db_alias).get_or_create(
            slug=slugify(division[0]), name=division[0], level=division[1]
        )


def populate_divisions_backwards(apps, schema_editor):
    Division = apps.get_model("rikishi", "Division")  # noqa: N806
    db_alias = schema_editor.connection.alias
    Division.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Makuuchi", "Makuuchi"),
                            ("Juryo", "Juryo"),
                            ("Makushita", "Makushita"),
                            ("Sandanme", "Sandanme"),
                            ("Jonidan", "Jonidan"),
                            ("Jonokuchi", "Jonokuchi"),
                            ("Mae-zumo", "Mae-zumo"),
                            ("Banzuke-gai", "Banzuke-gai"),
                        ],
                        max_length=12,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Shusshin",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("international", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Shusshin",
                "ordering": ["international", "name"],
            },
        ),
        migrations.CreateModel(
            name="Heya",
            fields=[
                (
                    "id",
                    AlphaIDField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("name_jp", models.CharField(max_length=32, unique=True)),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heya",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Heya",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Yokozuna", "Yokozuna"),
                            ("Ozeki", "Ozeki"),
                            ("Sekiwake", "Sekiwake"),
                            ("Komusubi", "Komusubi"),
                            ("Maegashira", "Maegashira"),
                            ("Juryo", "Juryo"),
                            ("Makushita", "Makushita"),
                            ("Sandanme", "Sandanme"),
                            ("Jonidan", "Jonidan"),
                            ("Jonokuchi", "Jonokuchi"),
                            ("Mae-zumo", "Mae-zumo"),
                            ("Banzuke-gai", "Banzuke-gai"),
                        ],
                        max_length=12,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "order",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("East", "East"), ("West", "West")],
                        max_length=4,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="rikishi.division",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "order", "direction"],
            },
        ),
        migrations.CreateModel(
            name="Rikishi",
            fields=[
                (
                    "id",
                    AlphaIDField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("name_jp", models.CharField(max_length=64, unique=True)),
                ("birth_date", models.DateField()),
                ("debut", models.DateField(blank=True, null=True)),
                ("intai", models.DateField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "heya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rikishi",
                        to="rikishi.heya",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rikishi",
                        to="rikishi.rank",
                    ),
                ),
                (
                    "shusshin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rikishi",
                        to="rikishi.shusshin",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rikishi",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(
            populate_divisions_forwards, populate_divisions_backwards
        ),
    ]
