# Generated by Django 5.0.7 on 2024-08-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_gamedate"),
        ("rikishi", "0003_alter_shusshin_prefecture"),
    ]

    operations = [
        migrations.CreateModel(
            name="RikishiStats",
            fields=[
                (
                    "rikishi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="rikishi.rikishi",
                    ),
                ),
                ("potential", models.PositiveIntegerField()),
                ("xp", models.PositiveIntegerField(default=0)),
                ("strength", models.PositiveIntegerField(default=1)),
                ("technique", models.PositiveIntegerField(default=1)),
                ("balance", models.PositiveIntegerField(default=1)),
                ("endurance", models.PositiveIntegerField(default=1)),
                ("mental", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="rikishi",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="rikishi",
            name="height",
        ),
        migrations.RemoveField(
            model_name="rikishi",
            name="weight",
        ),
        migrations.AlterField(
            model_name="rikishi",
            name="debut",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debut",
                to="base.gamedate",
            ),
        ),
        migrations.AlterField(
            model_name="rikishi",
            name="intai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intai",
                to="base.gamedate",
            ),
        ),
    ]
