# Generated by Django 5.0.7 on 2024-09-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heya", "0001_initial"),
        ("rikishi", "0004_rikishistats_remove_rikishi_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rikishi",
            name="heya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rikishi",
                to="heya.heya",
            ),
        ),
        migrations.DeleteModel(
            name="Heya",
        ),
    ]
