# Generated by Django 5.0.7 on 2024-09-30 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import base.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Heya",
            fields=[
                (
                    "id",
                    base.models.AlphaIDField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("name_jp", models.CharField(max_length=32, unique=True)),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heya",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Heya",
                "ordering": ["name"],
            },
        ),
    ]
