# Generated by Django 5.0.7 on 2024-08-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameDate",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("day", models.PositiveIntegerField()),
            ],
        ),
    ]
