# Generated by Django 5.0.7 on 2024-07-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMonth",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("number", models.PositiveIntegerField()),
            ],
        ),
    ]
