# Generated by Django 5.0.7 on 2024-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rikishi",
            "0002_alter_shusshin_options_remove_shusshin_international_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shusshin",
            name="prefecture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tokyo", "Tokyo"),
                    ("Hokkaido", "Hokkaido"),
                    ("Osaka", "Osaka"),
                    ("Aichi", "Aichi"),
                    ("Fukuoka", "Fukuoka"),
                    ("Aomori", "Aomori"),
                    ("Hyogo", "Hyogo"),
                    ("Kagoshima", "Kagoshima"),
                    ("Kanagawa", "Kanagawa"),
                    ("Chiba", "Chiba"),
                    ("Saitama", "Saitama"),
                    ("Ibaraki", "Ibaraki"),
                    ("Kumamoto", "Kumamoto"),
                    ("Shizuoka", "Shizuoka"),
                    ("Akita", "Akita"),
                    ("Niigata", "Niigata"),
                    ("Nagasaki", "Nagasaki"),
                    ("Fukushima", "Fukushima"),
                    ("Miyagi", "Miyagi"),
                    ("Miyazaki", "Miyazaki"),
                    ("Gifu", "Gifu"),
                    ("Mie", "Mie"),
                    ("Ehime", "Ehime"),
                    ("Yamaguchi", "Yamaguchi"),
                    ("Tochigi", "Tochigi"),
                    ("Saga", "Saga"),
                    ("Gunma", "Gunma"),
                    ("Yamagata", "Yamagata"),
                    ("Oita", "Oita"),
                    ("Kyoto", "Kyoto"),
                    ("Iwate", "Iwate"),
                    ("Ishikawa", "Ishikawa"),
                    ("Hiroshima", "Hiroshima"),
                    ("Kochi", "Kochi"),
                    ("Nagano", "Nagano"),
                    ("Okinawa", "Okinawa"),
                    ("Yamanashi", "Yamanashi"),
                    ("Okayama", "Okayama"),
                    ("Wakayama", "Wakayama"),
                    ("Toyama", "Toyama"),
                    ("Nara", "Nara"),
                    ("Fukui", "Fukui"),
                    ("Kagawa", "Kagawa"),
                    ("Tokushima", "Tokushima"),
                    ("Shimane", "Shimane"),
                    ("Shiga", "Shiga"),
                    ("Tottori", "Tottori"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
